### ISSUE TITLE
Command-line argument parsing example does not compile

### ISSUE THREAD

**Issue by djmattyg007** [tiehuis/zig-rosetta#3]
When I try to run the example code in the command-line argument parsing example, I get the following error:

```
./hr.zig:10:28: error: container 'std.os' has no member called 'argsAlloc'
    const args = try std.os.argsAlloc(allocator);
```

**Comment by tiehuis** [comment]
Most of the code here is targeting a much older zig version. I imagine most examples will need to be scoured through and changed to fit. I will probably hold off until things stabilize more since I personally unfortunately don't have the time to keep these up to date right now.
